##############################################################################
# Global Options
##############################################################################
# default_language_version:
#  python: python3.11
# exclude: "^demo_data|^dist|^docs|^venv"

# To update the version of the hooks to use and update 'pre-commit' configuration file then run.
#   $ pre-commit autoupdate
#
# The configuration options for hooks is in: pyproject.toml.


##############################################################################
# Hooks
##############################################################################
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        description: "Prevent giant files from being committed."
      - id: requirements-txt-fixer
        description: "Sorts entries in requirements.txt."
      - id: check-executables-have-shebangs
        description: "Ensures that (non-binary) executables have a shebang."
      - id: trailing-whitespace
        description: "Trims trailing whitespace."
      - id: end-of-file-fixer
        description: "Makes sure files end in a newline and only a newline"
      - id: detect-private-key
        description: "Checks for the existence of private keys."

  - repo: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools.git
    rev: rh-pre-commit-2.3.2
    hooks:
      # Docs:
      #   - https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit
      #   - https://source.redhat.com/departments/operations/it-information-security/leaktk/leaktk_guides/rh_pre_commit_attestation
      # - id: rh-pre-commit.commit-msg # Optional for commit-msg attestation
      - id: rh-pre-commit
        description: "The utility rh-pre-commit is a git pre-commit hook offered by InfoSec to all Red Hatters that scans code for secrets before they are committed and blocks the commit if any are detected."

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        description: "The utility shellcheck is a static analysis tool for shell scripts."
        args: ["--exclude=SC1091"]

  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.1
    hooks:
      - id: bashate
        description: "The utility bashate is an automated style checker for bash scripts "
        args: ["--ignore=E006"]

  - repo: https://github.com/codespell-project/codespell
    # To run 'codespell' manually and fix typos:
    #   $ ~/.cache/pre-commit/<cache dir>/py_env-python3.9/bin/codespell -w <path to file or files>
    rev: v2.4.1
    hooks:
      - id: codespell
        description: "Fix common misspellings in text files (including source code)."
        args: ["-f"]
