;;; cache.el --- Package State Caching System -*- lexical-binding: t -*-
;;; Commentary:
;;      Package state caching for offline functionality and faster startup.
;;      Provides intelligent cache management with freshness validation.

(require 'core-constants)
(require 'core-utils)

(with-load-timing
 "cache.el"

 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 ;; Package State Caching Configuration
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 (defvar
  package-state-cache-file
  (expand-file-name "package-state-cache.el" user-emacs-directory)
  "File to cache working package archive contents.")

 (defvar
  package-cache-max-age (* 7 24 60 60) ; 7 days in seconds
  "Maximum age of package cache before considering it stale.")

 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 ;; Cache Management Functions
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 (defun
  package-cache-fresh-p () "Check if package cache exists and is recent enough to use."
  (when
   (file-exists-p package-state-cache-file)
   (let ((cache-age
          (float-time
           (time-subtract
            (current-time)
            (file-attribute-modification-time (file-attributes package-state-cache-file))))))
     (< cache-age package-cache-max-age))))

 (defun
  save-package-state () "Cache current working package configuration to disk."
  (when
   (and
    package-archive-contents
    (> (length package-archive-contents) 10)) ; Sanity check
   (condition-case err
       (let ((cache-timestamp (current-time))
             (package-count (length package-archive-contents)))
         (with-temp-file
          package-state-cache-file
          (insert ";;; Cached package archive contents\n")
          (insert ";;; Generated by package-cache.el\n")
          (insert (format ";;; Cache created: %s\n" (current-time-string)))
          (insert (format ";;; Package count: %d\n" package-count))
          (insert ";;; This is a timestamp marker for cache freshness validation\n")
          (insert (format "(setq package-cache-timestamp '%S)\n" cache-timestamp))
          (insert (format "(setq package-cache-count %d)\n" package-count))
          (insert ";; Note: Actual package data loaded from built-in archives\n"))
         (message "📁  Package state cached (%d packages)" package-count))
     (error
      (message "⚠️  Failed to save package cache: %s" (error-message-string err))))))

 (defun
  load-cached-package-state () "Load cached package state using built-in package system."
  (when
   (file-exists-p package-state-cache-file)
   (condition-case err
       (progn
        ;; Load cache metadata
        (load package-state-cache-file)
        ;; Use package system's built-in caching instead of custom serialization
        (package-activate-all)
        (when
         (> (length package-alist) 0)
         (let ((cache-age
                (float-time
                 (time-subtract
                  (current-time)
                  (file-attribute-modification-time (file-attributes package-state-cache-file))))))
           (message
            "📁  Using cached package activation (%d packages, %.1f days old)"
            (length package-alist)
            (/ cache-age 86400)))))
     (error
      (message "⚠️  Failed to load package cache: %s" (error-message-string err))))))

 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 ;; Cache Utility Functions
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 (defun
  package-cache-info () "Display information about the package cache." (interactive)
  (if
   (file-exists-p package-state-cache-file)
   (let ((cache-age
          (float-time
           (time-subtract
            (current-time)
            (file-attribute-modification-time (file-attributes package-state-cache-file)))))
         (file-size (file-attribute-size (file-attributes package-state-cache-file))))
     (message
      "📁  Package cache: %.1f days old, %d bytes, %s"
      (/ cache-age 86400)
      file-size
      (if (package-cache-fresh-p) "FRESH" "STALE")))
   (message "📁  No package cache found")))

 (defun
  package-cache-clear () "Clear the package cache file." (interactive)
  (when
   (file-exists-p package-state-cache-file)
   (delete-file package-state-cache-file)
   (message "📁  Package cache cleared")))

 ;; Make this module available for loading with (require 'package-system/cache)
 (provide 'package-system/cache))
